config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  post 'simple_pages/thank_you'
  get 'simple_pages/contact'
  get 'orders/index'
  get 'products/index'
  root 'simple_pages#landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments , dependent: :destroy
  has_one_attached :image
  validates :name, presence: true

  def self.search(search_term)
    Product.where("name LIKE ?", "%#{search_term}%")
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.paginate(page: params[:page], per_page: 4)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
    end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
      <div>
        <%= comment.user.first_name %>, <%= "#{time_ago_in_words(comment.created_at)} ago" %>
        <% if signed_in? && current_user.admin? %>
          <%= link_to 'Destroy', product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    <p class="stars rated" data-score="<%= comment.rating %>"></p>
    <p>
      <%= comment.body %>
    </p>
    <% end %>
   <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
  <%= form.label :price %><br>
  $<%= form.text_field :price %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
    <div class="rating"></div>
  </p>
    <p>
      <%= f.submit "Submit" %>
    </p>

  <% end %>
<% end %>

app/views/products/_product.html.erb
  <tr class='col-md-3 col-sm-6'>
    <td style="display:block"><strong><%= product.name %></strong></td>
    <td style="display:block"><%= link_to image_tag(product.image, class: "img-fluid"), product if product.image.attached? %></td>
    <td>
    <% if product.comments != [] %>
      <p class="stars rated" data-score="<%= product.average_rating %>"></p>
    <% end %>
    </td>
    <td style="display:block"><%= product.description %></td>
    <td style="display:block"><strong><%= number_to_currency(product.price) %></strong></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td>
      <% if signed_in? && current_user.admin? %>
        <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p> 
      <% end %>
    </td>
  </tr>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>


  <tbody class='row'>
    <%# Scope  %>
    <%= render partial: "product", collection: @products %>
  </tbody>
</table>
<%= will_paginate @products %>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
<%= link_to image_tag(@product.image, style:'width:100%'), products_path %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong><%= number_to_currency(@product.price) %></strong>
</p>
<p>
    <strong>Avrage Raiting:</strong>

    <p class="stars rated" data-score="<%= @product.average_rating %>"></p>

</p>

<%= render partial: "comments" %>

<%= render 'new_comment' %>


<%= link_to 'Add to Order', orders_path %>

<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>