config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  post 'simple_pages/thank_you'
  get 'simple_pages/contact'
  get 'orders/index'
  get 'products/index'
  root 'simple_pages#landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DABI</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
  <nav>
      <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "Contact", simple_pages_contact_path %></li>
      <li><%= link_to "Dashboard", users_path %></li>
      <!-- fix later -->
      <li><%= link_to "Orders", orders_path %></li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to('Login', new_user_session_path, class: "nav-link") %>
      </li>
      <% end %>
    </ul>
  </nav>
<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p>

  <%= yield %>
  </body>
</html>